### PR TITLE
Enhance vm-virtio crate to better support fuse/virtiofs related projects

### PR DESCRIPTION
**Pull request by jiangliu**
This patch set aims to enhance the vm-virtio crate to better support fuse/virtiofs related projects.
The first ten patches have been submitted to rust-vmm/vm-virtio, and the last four patches may be hold  for a while until we reach an agreement in the rust-vmm community.

### CODE REVIEW

**Review by bergwolf — APPROVED** [review]

**Comment by sameo** [comment]
@jiangliu We are planning to split our vm-virtio crate into device vs core parts, see https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1361

Could you use your local branch for now, until we move forward with the split? And then rebase those changes on top of the split vm-virtio?

**Comment by jiangliu** [comment]
> @jiangliu We are planning to split our vm-virtio crate into device vs core parts, see [cloud-hypervisor/cloud-hypervisor#1361](https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1361)
> 
> Could you use your local branch for now, until we move forward with the split? And then rebase those changes on top of the split vm-virtio?

Actually we have integrate some cloud hypervisor specific changes into the patchset. And we have already sent those changes to rust-vmm/vm-virtio.

Is it OK to host this on dragonball branch? We are planning to open source some project to CNCF/dragonfly, so we need a public available git repo to host the vm-virtio crate.

**Comment by sameo** [comment]
> > @jiangliu We are planning to split our vm-virtio crate into device vs core parts, see [cloud-hypervisor/cloud-hypervisor#1361](https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1361)
> > Could you use your local branch for now, until we move forward with the split? And then rebase those changes on top of the split vm-virtio?
> 
> Actually we have integrate some cloud hypervisor specific changes into the patchset. And we have already sent those changes to rust-vmm/vm-virtio.
> 
> Is it OK to host this on dragonball branch? We are planning to open source some project to CNCF/dragonfly, so we need a public available git repo to host the vm-virtio crate.

Just checking: Is the plan to eventually switch to the rust-vmm virtio crate?
I just created a dragonball branch, please change your PR to go against it.

**Comment by jiangliu** [comment]
> > > @jiangliu We are planning to split our vm-virtio crate into device vs core parts, see [cloud-hypervisor/cloud-hypervisor#1361](https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1361)
> > > Could you use your local branch for now, until we move forward with the split? And then rebase those changes on top of the split vm-virtio?
> > 
> > 
> > Actually we have integrate some cloud hypervisor specific changes into the patchset. And we have already sent those changes to rust-vmm/vm-virtio.
> > Is it OK to host this on dragonball branch? We are planning to open source some project to CNCF/dragonfly, so we need a public available git repo to host the vm-virtio crate.
> 
> Just checking: Is the plan to eventually switch to the rust-vmm virtio crate?
> I just created a dragonball branch, please change your PR to go against it.

It's the preferred way to upstream all to rust-vmm, but we can't reach an agreement about the way to deal with GuestMemory objects. We prefer to passing a GuestMemory reference but Paolo prefers hold a GuestAddressSpace reference by the Queue.
All changes except this one should be upstreamed.

**Comment by jiangliu** [comment]
@sameo @sboeuf @arronwy I have updated the MR with a new patch to access all virtq data fields with atomic ops instead of read_obj/write_obj, which helps to solve the CVE caused by the vm-memory crate.
There's also another changes related to EVENT_IDX. Originally the's only one interface Queue::update_avail_event(). Now it's refined two interfaces: Queue::disable_notification() and Queue::enable_notification(). The typical way to use these interfaces are:
```rust
fn handle_queue_notification(&mut self) -> Result<()> {
     self.queue.disable_notification();
     self.process_queue();
     loop {
          self.queue.enable_notification();
          if !self.process_queue() {
                break;
          }
     }
}
```

**Comment by sameo** [comment]
Superseded by PR #3

**Pull request closed without merging**
